{
 "title": "New dashboard Copy",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "JVM Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"spring-prometheus-demo\"}) by (application)",
     "legendFormat": "JVM"
    },
    {
     "expr": "container_memory_usage_bytes{container=\"spring-prometheus-demo\"}",
     "legendFormat": "Container"
    },
    {
     "expr": "kube_pod_container_resource_requests_memory_bytes { \n container=\"spring-prometheus-demo\", job=\"kube-state-metrics\"\n }",
     "legendFormat": "Requests"
    },
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes { \n container=\"spring-prometheus-demo\", job=\"kube-state-metrics\"\n }",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Memory Used vs Limit",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_usage_bytes{\n container=\"spring-prometheus-demo\"\n }\n) by (container) / \nsum (kube_pod_container_resource_limits_memory_bytes { \n container=\"spring-prometheus-demo\"\n }\n) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Total Visitor Count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "visit_counter_total" }
   ]
  },
  {
   "title": "Visitor Rate (5 min)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ]
  }
 ]
}